-- ============================================================================
-- Wyjasnienia (podstawa prawna + uzasadnienie) dla 85 unikalnych pytan
-- podstawowych bez multimediow. Wygenerowane przez LLM na podstawie tresci
-- pytania i znanych przepisow (gl. ustawa Prawo o ruchu drogowym) -- NIE
-- traktowac jako ostateczne zrodlo prawdy, kolumna wyjasnienie_zweryfikowane
-- (z 0033) zostaje false do czasu przegladu przez instruktorow.
--
-- 3 pytania (25, 26, 83 z oryginalnej listy) maja tresc w formie "ktore z
-- ponizszych" mimo etykiety tak/nie -- oznaczone notatka do przeredagowania,
-- nie fabrykowano im realnego uzasadnienia bo pytanie w tej formie nie ma
-- jednoznacznej odpowiedzi tak/nie.
-- ============================================================================

update question set wyjasnienie = 'Art. 39 ust. 1 ustawy Prawo o ruchu drogowym nakłada obowiązek korzystania z pasów bezpieczeństwa podczas jazdy przez kierującego i pasażerów pojazdu wyposażonego w takie pasy.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy przed rozpoczęciem jazdy kierowca ma obowiązek zapiąć pasy bezpieczeństwa?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 26 ust. 3 pkt 1 ustawy Prawo o ruchu drogowym zabrania wyprzedzania pojazdu na przejściu dla pieszych i bezpośrednio przed nim — ograniczona widoczność pieszego wchodzącego na jezdnię czyni to szczególnie niebezpiecznym.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy wolno wyprzedzać na przejściu dla pieszych?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 22 ustawy Prawo o ruchu drogowym zabrania zawracania w tunelu — ograniczona widoczność i brak miejsca na manewr stwarzają wysokie ryzyko kolizji czołowej.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy w tunelu obowiązuje zakaz zawracania?' and poprawna = 'TAK';
update question set wyjasnienie = 'Zgodnie z przepisami o sygnalizacji świetlnej (rozporządzenie w sprawie znaków i sygnałów drogowych) czerwone światło oznacza zakaz wjazdu za sygnalizator lub linię zatrzymania.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy sygnał czerwony oznacza zakaz wjazdu za sygnalizator?' and poprawna = 'TAK';
update question set wyjasnienie = 'Cofanie jest manewrem szczególnie niebezpiecznym — kierujący cofający pojazd (w tym tramwaj) musi ustąpić pierwszeństwa innym uczestnikom ruchu, a nie odwrotnie.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas cofania tramwajem motorniczy ma pierwszeństwo przed innymi pojazdami i uczestnikami ruchu?' and poprawna = 'NIE';
update question set wyjasnienie = 'Gaśnica proszkowa jest przeznaczona m.in. do gaszenia pożarów cieczy palnych (grupa B), w tym paliw — to standardowe zalecenie pierwszej pomocy przy pożarze pojazdu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy wskazane jest użycie gaśnicy proszkowej do stłumienia palącego się paliwa, np. po kolizji z samochodem?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ustawy Prawo o ruchu drogowym nakłada obowiązek zatrzymania się i udzielenia pomocy ofiarom wypadku — obawa o utrudnienia w ruchu nie zwalnia z tego obowiązku.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierując tramwajem możesz opuścić miejsce wypadku drogowego, w którym jest ranny, by nie powodować utrudnień w ruchu?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 1 ustawy Prawo o ruchu drogowym nakłada na uczestnika wypadku obowiązek podjęcia czynności zapewniających bezpieczeństwo w miejscu zdarzenia (np. ostrzeżenie innych uczestników ruchu).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy jako uczestnik wypadku drogowego masz obowiązek podjąć działania służące zapewnieniu bezpieczeństwa w miejscu zdarzenia?' and poprawna = 'TAK';
update question set wyjasnienie = 'Ustawa o wychowaniu w trzeźwości oraz Prawo o ruchu drogowym określają jednolitą granicę stanu po użyciu alkoholu (0,2‰) dla wszystkich kierujących pojazdami, niezależnie od rodzaju pojazdu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczych obowiązuje taka sama norma dopuszczalnej zawartości alkoholu we krwi co pozostałych kierowców?' and poprawna = 'TAK';
update question set wyjasnienie = 'Producent leku wyraźnie zastrzega przeciwwskazanie do prowadzenia pojazdów — zignorowanie tej informacji narusza obowiązek zachowania sprawności psychofizycznej kierującego (art. 45 ustawy Prawo o ruchu drogowym w zakresie stanów wyłączających sprawną jazdę).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy przed rozpoczęciem pracy może przyjąć lek, w którego ulotce znajduje się następujący zapis "w czasie stosowania preparatu nie wolno prowadzić pojazdów"?' and poprawna = 'NIE';
update question set wyjasnienie = 'Odpowiedzialność za sprawność psychofizyczną przed jazdą spoczywa na kierującym — sprawdzenie ulotki leku jest podstawowym środkiem ostrożności.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy przed rozpoczęciem pracy powinien upewnić się, że przyjmowane przez niego leki nie mają przeciwwskazań do prowadzenia pojazdów?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 45 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym zabrania kierowania pojazdem (w tym tramwajem) osobie znajdującej się w stanie nietrzeźwości lub pod wpływem środka działającego podobnie do alkoholu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierowanie tramwajem pod wpływem środków działających tak jak alkohol jest zabronione?' and poprawna = 'TAK';
update question set wyjasnienie = 'Obowiązek zabezpieczenia pojazdu pozostawionego bez nadzoru (np. unieruchomienie, zamknięcie) wynika z ogólnej zasady odpowiedzialności kierującego za pojazd, analogicznie do art. 60 ustawy Prawo o ruchu drogowym dla pojazdów drogowych.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy wychodząc z tramwaju podczas postoju na pętli, powinieneś zabezpieczyć go przed uruchomieniem przez osoby niepowołane?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 3 ustawy Prawo o ruchu drogowym (zasada ograniczonego zaufania) wymaga szczególnej ostrożności wobec dzieci jako uczestników ruchu o nieprzewidywalnym zachowaniu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierując tramwajem powinieneś spodziewać się, że bawiące się niedaleko torów dzieci mogą zachować się nieprzewidywalnie i konieczne będzie zmniejszenie prędkości lub zatrzymanie pojazdu?' and poprawna = 'TAK';
update question set wyjasnienie = 'Bezpieczeństwo pasażerów jest nadrzędne — motorniczy nie może dopuścić do sytuacji zagrażającej ich bezpieczeństwu nawet w celu przywrócenia płynności ruchu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas długotrwałej awarii możesz pozwolić pasażerom opuścić tramwaj, nawet jeśli może to utrudnić ruch lub narazić ich na niebezpieczeństwo?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 2 ustawy Prawo o ruchu drogowym nakłada obowiązek podania swoich danych personalnych innym uczestnikom zdarzenia na ich żądanie.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy jako motorniczy jesteś zobowiązany do podania swoich danych personalnych pasażerowi uczestniczącemu w wypadku?' and poprawna = 'TAK';
update question set wyjasnienie = 'Dane pracodawcy i ubezpieczyciela są niezbędne poszkodowanemu do dochodzenia roszczeń z OC — obowiązek ten uzupełnia obowiązek podania danych osobowych z art. 44 ustawy Prawo o ruchu drogowym.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy jesteś zobowiązany podać dane firmy, w której pracujesz oraz dane dotyczące ubezpieczyciela tramwaju pasażerowi, który uczestniczy w wypadku?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ustawy Prawo o ruchu drogowym oraz art. 162 Kodeksu karnego (nieudzielenie pomocy) nie uzależniają obowiązku udzielenia pomocy od posiadanego przeszkolenia — wystarczy działać w miarę własnych możliwości.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy jako motorniczy, niezależnie od tego, czy zostałeś przeszkolony, czy nie, jesteś zobowiązany udzielić niezbędnej pomocy ofiarom wypadku?' and poprawna = 'TAK';
update question set wyjasnienie = 'Zmęczenie jest powszechnie uznanym w materiałach WORD czynnikiem obniżającym sprawność psychomotoryczną kierowcy w sposób analogiczny do działania alkoholu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy zmęczenie może powodować skutki zbliżone do działania alkoholu, takie jak obniżona możliwość koncentracji oraz wydłużony czas reakcji?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ustawy Prawo o ruchu drogowym wymaga pozostania na miejscu wypadku do czasu przybycia Policji, nie tylko "służb nadzoru ruchu" — samodzielne oddalenie się bez zgody Policji jest niedopuszczalne.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku, w którym są zabici lub ranni, masz prawo oddalić się z miejsca wypadku, gdy przybędą służby nadzoru ruchu?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 1 pkt 3 ustawy Prawo o ruchu drogowym zabrania podejmowania czynności mogących utrudnić ustalenie przebiegu wypadku (np. przemieszczania pojazdów) do czasu przybycia Policji, poza działaniami ratującymi życie.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku, w którym są zabici lub ranni, masz prawo zacząć samodzielnie usuwać jego skutki - sprzątać, przygotowywać tramwaj do holowania itp.?' and poprawna = 'NIE';
update question set wyjasnienie = 'Środki odurzające zawsze pogarszają, nigdy nie poprawiają, zdolność oceny ryzyka i czas reakcji kierowcy — to podstawowa wiedza z zakresu bezpieczeństwa ruchu drogowego.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy zażycie przez prowadzącego pojazd niewielkiej ilości narkotyku wpływa na poprawę zdolności do prawidłowej oceny ryzyka na drodze?' and poprawna = 'NIE';
update question set wyjasnienie = 'Alkohol ogranicza zdolność do tzw. podzielności uwagi (wykonywania kilku czynności jednocześnie) — to jeden z podstawowych, udokumentowanych skutków jego działania na kierowców.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący pojazdem po spożyciu alkoholu, może mieć trudności w jednoczesnym wykonywaniu dwóch i więcej czynności?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 162 Kodeksu karnego (nieudzielenie pomocy) obowiązuje niezależnie od kwalifikacji medycznych — wystarczy udzielić pomocy w zakresie własnych możliwości i wezwać fachową pomoc.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy będąc uczestnikiem wypadku drogowego, masz obowiązek udzielenia pomocy rannym nawet, jeśli nie masz kwalifikacji medycznych?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 45 ust. 2 pkt 1 ustawy Prawo o ruchu drogowym zabrania kierującemu pojazdem korzystania podczas jazdy z telefonu wymagającego trzymania słuchawki lub mikrofonu w ręku.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczemu wolno podczas kierowania tramwajem korzystać z trzymanego w ręku telefonu komórkowego?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 45 ust. 2 pkt 1 ustawy Prawo o ruchu drogowym zabrania jedynie korzystania z telefonu wymagającego trzymania go w ręku — zestaw głośnomówiący jest dozwolony.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas kierowania tramwajem dozwolone jest korzystanie z telefonu komórkowego, jeśli nie wymaga to trzymania aparatu w ręku?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym nakłada obowiązek natychmiastowego zatrzymania pojazdu, o ile nie zagraża to bezpieczeństwu ruchu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku drogowym, w którym są ranni, masz obowiązek niezwłocznie zatrzymać tramwaj, nie powodując przy tym zagrożenia?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ust. 3 ustawy Prawo o ruchu drogowym nakłada obowiązek usunięcia pojazdu z miejsca zdarzenia, jeśli nie ma zabitych ani rannych, by nie tamować ruchu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy masz obowiązek, o ile to możliwe, usunąć tramwaj z miejsca wypadku, w którym nie ma rannych, ani zabitych.?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ust. 2 ustawy Prawo o ruchu drogowym nakłada obowiązek podania danych personalnych na żądanie osoby uczestniczącej w zdarzeniu, w tym pasażera.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku, masz obowiązek podać swoje dane personalne na żądanie pasażera, który także uczestniczył w zdarzeniu?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ustawy Prawo o ruchu drogowym wymaga wezwania Policji obowiązkowo tylko przy wypadku ze skutkiem śmiertelnym lub obrażeniami — przy szkodzie wyłącznie materialnej wezwanie Policji jest fakultatywne, chyba że strony nie mogą ustalić okoliczności zdarzenia.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku drogowym, masz obowiązek powiadomić policję, jeśli w wypadku nie ma zabitych lub rannych?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 1 pkt 4 ustawy Prawo o ruchu drogowym nakłada obowiązek wezwania Policji i pogotowia ratunkowego, gdy w wypadku są zabici lub ranni.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku drogowym, masz obowiązek powiadomić policję i wezwać zespół ratownictwa medycznego, jeśli w wypadku są osoby zabite lub ranne?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 45 ust. 2 pkt 1 ustawy Prawo o ruchu drogowym wprost zabrania korzystania podczas jazdy z telefonu wymagającego trzymania go w ręku.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas kierowania tramwajem masz prawo rozmawiać przez telefon komórkowy, wymagający trzymania słuchawki lub mikrofonu w ręku?' and poprawna = 'NIE';
update question set wyjasnienie = 'Zabezpieczenie tramwaju przed samoczynnym ruchem (np. hamulcem postojowym) przed wyjściem motorniczego do ręcznego przełożenia zwrotnicy jest podstawową zasadą bezpieczeństwa pracy motorniczego.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy przed ręcznym przełożeniem zwrotnicy motorniczy powinien "zaparkować" tramwaj?' and poprawna = 'TAK';
update question set wyjasnienie = 'Pojazd pozostawiony bez zabezpieczenia stwarza ryzyko niekontrolowanego ruchu lub uruchomienia przez osoby postronne — obowiązek zabezpieczenia dotyczy każdego postoju bez nadzoru.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy w czasie postoju na pętli masz prawo opuścić tramwaj bez zabezpieczenia go?' and poprawna = 'NIE';
update question set wyjasnienie = '100 km/h to ok. 27,8 m/s (100 000 m / 3600 s) — prosty przelicznik jednostek prędkości, zaokrąglany do ok. 28 m/s.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy jadąc z prędkością 100 km/h pojazd pokonuje około 28 metrów na sekundę?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 45 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym zabrania kierowania pojazdem w stanie po użyciu alkoholu niezależnie od subiektywnego samopoczucia kierującego.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy ma prawo prowadzić tramwaj w stanie po użyciu alkoholu (np. po wypiciu jednego piwa), jeśli czuje się dobrze?' and poprawna = 'NIE';
update question set wyjasnienie = 'Przepisy o czasie pracy kierowców/motorniczych gwarantują minimalny nieprzerwany odpoczynek dobowy — sumowanie godzin ze wszystkich form zatrudnienia nie może go skracać poniżej ustawowego minimum.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy, uwzględniając wszystkie formy zatrudnienia, może odpoczywać krócej niż 11 godzin na dobę?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 45 ust. 2 pkt 1 ustawy Prawo o ruchu drogowym zakazuje wyłącznie korzystania z telefonu wymagającego trzymania go w ręku — zestaw bezprzewodowy/głośnomówiący jest dozwolony.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas kierowania tramwajem masz prawo rozmawiać przez telefon komórkowy, jeżeli nie trzymasz słuchawki i mikrofonu w ręku?' and poprawna = 'TAK';
update question set wyjasnienie = 'Przepisy o czasie pracy kierowców gwarantują cotygodniowy nieprzerwany odpoczynek w wymiarze co najmniej 35 godzin, analogicznie do rozporządzenia (WE) 561/2006 dla kierowców zawodowych.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczemu wykonującemu przewozy pasażerskie, przysługuje prawo do co najmniej 35 godzin nieprzerwanego odpoczynku w tygodniu?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 24 ustawy Prawo o ruchu drogowym wymaga zachowania odstępu 1 m tylko wobec omijanego pieszego, rowerzysty, hulajnogi itp. — wobec przeszkód statycznych wymagany jest jedynie odstęp "odpowiedni", nie sztywno 1 m.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy w każdym przypadku masz obowiązek zachować odległość co najmniej 1 metra od omijanego pojazdu, uczestnika ruchu lub przeszkody?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 23 ust. 1 pkt 3 ustawy Prawo o ruchu drogowym wymaga, by kierujący cofający pojazd, który nie ma dostatecznej widoczności do tyłu, zapewnił sobie pomoc innej osoby.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy, który nie ma możliwości obserwacji drogi za tramwajem, może cofać, nie zapewniając sobie pomocy innej osoby?' and poprawna = 'NIE';
update question set wyjasnienie = 'Każdy manewr cofania wymaga wcześniejszego upewnienia się o bezpieczeństwie — pominięcie tego kroku łamie podstawową zasadę ostrożności przy cofaniu (art. 23 ustawy Prawo o ruchu drogowym).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy motorniczy, który źle przełożył zwrotnicę i zauważył to ok. 1 m za nią, ma prawo wycofać tramwaj nie sprawdzając, czy nie spowoduje tym zagrożenia?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 57 ustawy Prawo o ruchu drogowym nakłada obowiązek szczególnej ostrożności przy omijaniu pojazdu przewożącego zorganizowaną grupę dzieci lub młodzieży w trakcie wsiadania/wysiadania.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy masz obowiązek zachować szczególną ostrożność, gdy omijasz pojazd przewożący zorganizowaną grupę dzieci do 18 lat, które z niego wysiadają?' and poprawna = 'TAK';
update question set wyjasnienie = 'Obowiązek zabezpieczenia pojazdu dotyczy sytuacji, gdy pojazd jest pozostawiony bez nadzoru — obecność motorniczego w kabinie stanowi już nadzór, więc bezwzględne zamknięcie wszystkich drzwi nie jest wymagane.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy ze względu na nakaz zabezpieczenia pojazdu w czasie postoju wszystkie drzwi tramwaju powinny pozostać zamknięte, gdy w kabinie przebywa motorniczy?' and poprawna = 'NIE';
update question set wyjasnienie = 'To pytanie ma formę opisową ("jak postąpisz"), nie tak/nie — w oryginalnym banku prawdopodobnie miało warianty odpowiedzi A/B/C; odpowiedź NIE dotyczy błędnej/niebezpiecznej procedury reagowania na pożar instalacji elektrycznej (np. gaszenia wodą).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Kierujesz pojazdem szynowym. Jak postąpisz, gdy zauważysz pożar instalacji elektrycznej?' and poprawna = 'NIE';
update question set wyjasnienie = 'Alkohol powoduje tzw. efekt "tunelowego widzenia" — zawężenie pola widzenia kierowcy, co jest szeroko udokumentowanym skutkiem jego działania.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy spożyty alkohol wpływa na zmianę pola widzenia kierującego pojazdem?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 60 ust. 2 pkt 1 ustawy Prawo o ruchu drogowym nakłada obowiązek zabezpieczenia pojazdu pozostawionego na drodze o pochyleniu przed samoczynnym przemieszczeniem (np. hamulec postojowy, bieg, klin).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy masz obowiązek zabezpieczyć przed stoczeniem się pojazd zaparkowany na wzniesieniu?' and poprawna = 'TAK';
update question set wyjasnienie = 'Zapory na przejazdach kolejowych są konstrukcyjnie łamliwe, by pojazd uwięziony między nimi mógł je sforsować i opuścić torowisko w sytuacji zagrożenia.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy konstrukcja zapór pozwala na ich wyłamanie, jeśli pojazd znalazł się na przejeździe kolejowym pomiędzy zamkniętymi zaporami.' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 24 ustawy Prawo o ruchu drogowym wymaga, by omijanie odbywało się z zachowaniem bezpiecznego odstępu, co w razie potrzeby oznacza konieczność zmniejszenia prędkości.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący pojazdem podczas omijania pieszego musi w razie potrzeby zmniejszyć prędkość?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 24 ust. 8 ustawy Prawo o ruchu drogowym dopuszcza na jezdni jednokierunkowej wyprzedzanie pojazdu szynowego z lewej strony, gdy nie ma dla niego wydzielonego pasa lub torowiska po prawej.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy na jezdni jednokierunkowej dopuszcza się wyprzedzanie pojazdu szynowego z jego lewej strony?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 6 ustawy Prawo o ruchu drogowym nakazuje stosowanie się do poleceń i sygnałów osób kierujących ruchem lub upoważnionych do jego kontroli, do których zalicza się pilota pojazdu nienormatywnego w zakresie zabezpieczenia przejazdu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy masz obowiązek stosować się do poleceń lub sygnałów dawanych przez pilota pojazdu nienormatywnego?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 45 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym zabrania kierowania jakimkolwiek pojazdem pod wpływem środka odurzającego, bez rozróżnienia na "twarde" i "miękkie" narkotyki.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy możesz kierować czterokołowcem lekkim po użyciu narkotyków miękkich czyli np. marihuany?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 2 ustawy Prawo o ruchu drogowym daje uczestnikom zdarzenia prawo żądania od siebie nawzajem danych personalnych.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy poszkodowany w wypadku drogowym ma prawo żądać danych personalnych sprawcy?' and poprawna = 'TAK';
update question set wyjasnienie = 'Koc termoizolacyjny ogranicza utratę ciepła przez poszkodowanego — to standardowy element pierwszej pomocy zapobiegający hipotermii pourazowej.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy przykrywając ofiarę wypadku kocem termoizolacyjnym, ochronisz ją przed wychłodzeniem?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 44 ust. 1 pkt 3 ustawy Prawo o ruchu drogowym zabrania podejmowania czynności mogących utrudnić ustalenie przebiegu wypadku (w tym przemieszczania pojazdu) do czasu przybycia Policji, gdy są ofiary.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy masz obowiązek usunąć z drogi motorower, gdy uczestniczysz w wypadku, w którym jest zabity lub ranny?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 44 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym nakłada obowiązek niezwłocznego zatrzymania pojazdu, o ile nie stwarza to zagrożenia.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy uczestnicząc w wypadku drogowym masz obowiązek zatrzymać motorower nie powodując zagrożenia bezpieczeństwa?' and poprawna = 'TAK';
update question set wyjasnienie = 'Przy wypadku bez ofiar (kolizji) wezwanie Policji jest obowiązkowe tylko, gdy strony nie mogą same ustalić okoliczności zdarzenia lub są co do nich niezgodne — w pozostałych przypadkach jest fakultatywne.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy biorąc udział w wypadku, w którym nie ma rannych, masz obowiązek wezwać Policję?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 45 ust. 1 pkt 1 ustawy Prawo o ruchu drogowym zabrania kierowania jakimkolwiek pojazdem, w tym motorowerem, w stanie po użyciu alkoholu lub podobnie działającego środka, bez wyjątków.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierowanie motorowerem w stanie po użyciu alkoholu lub środka działającego podobnie do alkoholu jest zawsze zabronione?' and poprawna = 'TAK';
update question set wyjasnienie = 'To udokumentowane, klasyczne skutki działania alkoholu na kierowcę — fałszywa pewność siebie, zaburzona percepcja odległości i wydłużony czas reakcji.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy alkohol powoduje u kierującego motorowerem nadmierną pewność siebie prowadzącą do brawury na drodze oraz zaburza ocenę odległości i wydłuża czas reakcji?' and poprawna = 'TAK';
update question set wyjasnienie = 'Alkohol upośledza zdolność oceny ryzyka niezależnie od rodzaju prowadzonego pojazdu, w tym czterokołowca.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy spożycie alkoholu przez kierującego pogarsza zdolność do prawidłowej oceny ryzyka na drodze podczas jazdy czterokołowcem?' and poprawna = 'TAK';
update question set wyjasnienie = 'Zasada ostrożności nakazuje powstrzymanie się od jazdy przy niepewności co do wpływu leku na sprawność psychofizyczną — ryzyko nieznanego działania obciąża kierującego.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy powinieneś powstrzymać się od kierowania motorowerem, jeżeli zażyłeś leki, o których nie masz wiedzy lub informacji, jaki mają wpływ na organizm i bezpieczne kierowanie pojazdami?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 26 ust. 7 ustawy Prawo o ruchu drogowym nakłada obowiązek zatrzymania pojazdu, by umożliwić przejście osobie o widocznie ograniczonej sprawności ruchowej.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy dojeżdżając do przejścia dla pieszych, na które wchodzi osoba niepełnosprawna, używająca specjalnego znaku lub osoba o widocznej ograniczonej sprawności ruchowej, powinieneś wziąć pod uwagę, że będziesz musiał zatrzymać pojazd?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 28 ustawy Prawo o ruchu drogowym oraz zasada szczególnej ostrożności na przejazdach kolejowych nakładają obowiązek niezwłocznego ostrzeżenia kierującego pojazdem szynowym o przeszkodzie na torowisku.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy w razie braku możliwości usunięcia uszkodzonego pojazdu z torowiska masz obowiązek ostrzec o zagrożeniu kierującego pociągiem?' and poprawna = 'TAK';
update question set wyjasnienie = 'Pierwszą czynnością powinno być usunięcie ludzi z zagrożonej strefy i próba usunięcia pojazdu z torowiska, a dopiero potem/jednocześnie ostrzeżenie maszynisty — priorytetem jest bezpieczeństwo osób.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy w razie unieruchomienia pojazdu na przejeździe kolejowym masz obowiązek w pierwszej kolejności ostrzec o niebezpieczeństwie kierującego pojazdem szynowym?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 28 ust. 2 ustawy Prawo o ruchu drogowym zabrania wjazdu na przejazd, gdy zapory lub półzapory są opuszczane lub podniesione niecałkowicie — rozpoczęte opuszczanie oznacza bezwzględny zakaz wjazdu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy, zachowując zwiększoną uwagę, masz prawo wjechać na przejazd kolejowy, jeżeli opuszczanie półzapór dopiero się rozpoczęło?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 26 ust. 7 ustawy Prawo o ruchu drogowym rozciąga obowiązek ustąpienia pierwszeństwa osobie o widocznie ograniczonej sprawności ruchowej także poza wyznaczonym przejściem dla pieszych.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy podczas przechodzenia przez jezdnię, poza przejściem dla pieszych, przez osobę  o widocznej ograniczonej sprawności ruchowej, jesteś obowiązany zatrzymać się, aby umożliwić jej przejście ?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 29 ust. 2 pkt 3 ustawy Prawo o ruchu drogowym dopuszcza/zaleca używanie sygnału dźwiękowego w warunkach ograniczonej widoczności (mgła) poza obszarem zabudowanym w celu ostrzeżenia innych uczestników ruchu.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący pojazdem silnikowym w czasie wyprzedzania pieszego, podczas mgły poza obszarem zabudowanym, powinien dawać krótkotrwałe sygnały dźwiękowe?' and poprawna = 'TAK';
update question set wyjasnienie = 'Analogicznie do wyprzedzania — w warunkach mgły poza obszarem zabudowanym sygnał dźwiękowy podczas omijania pieszego zwiększa jego świadomość o nadjeżdżającym pojeździe.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący pojazdem silnikowym w czasie omijania pieszego, podczas mgły poza obszarem zabudowanym, powinien dawać krótkotrwałe sygnały dźwiękowe?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 26 ust. 4-5 ustawy Prawo o ruchu drogowym nakłada obowiązek ustąpienia pierwszeństwa i zatrzymania się przy przystanku bez wysepki, gdy pasażerowie muszą wejść na jezdnię, by dotrzeć do pojazdu komunikacji.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący pojazdem przejeżdżając obok przystanku tramwajowego i autobusowego komunikacji miejskiej, nie wyposażonego w wyspę dla pasażerów i wymagającego wyjścia pasażerów na jezdnię, ma obowiązek zatrzymać pojazd w takim miejscu, aby zapewnić pieszemu swobodne dojście do stojącego na tym przystanku autobusu?' and poprawna = 'TAK';
update question set wyjasnienie = 'To pytanie sformułowane przeczące brzmi myląco — w rzeczywistości art. 19 ust. 1 ustawy Prawo o ruchu drogowym WŁAŚNIE nakłada taki obowiązek na kierującego; odpowiedź NIE w oryginalnym banku może wynikać z innej, dosłownej wersji pytania (np. wyjątku dla pojazdów uprzywilejowanych) — zalecana priorytetowa weryfikacja przez instruktora.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy każdy kierujący pojazdem ma obowiązek jechać z prędkością zapewniającą panowanie nad pojazdem ?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 19 ust. 1 ustawy Prawo o ruchu drogowym wymaga dostosowania prędkości do warunków (widoczność, ukształtowanie drogi) — maksymalny limit administracyjny nie oznacza, że taka prędkość jest zawsze bezpieczna.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Kierując pojazdem poza obszarem zabudowanym w nocy na nieoświetlonej, krętej drodze, aby uniknąć najechania na nieoświetloną przeszkodę nie powinno się jechać z wykorzystaniem maksymalnego limitu prędkości. Czy to prawda ?' and poprawna = 'TAK';
update question set wyjasnienie = 'Wysoka prędkość skraca czas, w którym inny uczestnik ruchu może zauważyć i prawidłowo ocenić odległość/prędkość nadjeżdżającego pojazdu — to znany efekt psychofizyczny wykorzystywany w materiałach szkoleniowych WORD.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy pojazd poruszający się z dużą prędkością może być trudniejszy do zauważenia przez innych uczestników ruchu drogowego?' and poprawna = 'TAK';
update question set wyjasnienie = 'Przy prędkości 120 km/h pojazd pokonuje ok. 33 m w ciągu 1 sekundy — opóźnienie reakcji o 1 s realnie wydłuża drogę zatrzymania o taki rząd wielkości.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy opóźnienie reakcji kierowcy o 1 sekundę przy prędkości dopuszczalnej na drodze ekspresowej może zwiększyć drogę zatrzymania o kilkadziesiąt metrów ?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 33a ust. 3 ustawy Prawo o ruchu drogowym zabrania przewożenia innej osoby, zwierzęcia lub ładunku hulajnogą elektryczną.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący hulajnogą elektryczną może przewozić pasażera?' and poprawna = 'NIE';
update question set wyjasnienie = 'Przepisy nie przewidują takiego zezwolenia — ciągnięcie osoby na urządzeniu wspomagającym ruch (np. wrotkach) za pojazdem jest zakazane ze względów bezpieczeństwa.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierującemu pojazdem zezwala się na ciągnięcie osoby korzystającej z urządzenia wspomagającego ruch?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 33a ust. 4 ustawy Prawo o ruchu drogowym dopuszcza wyjątkowo korzystanie z drogi dla pieszych (z prędkością pieszego) w razie braku drogi dla rowerów/pasa ruchu dla hulajnóg.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący hulajnogą elektryczną może wyjątkowo korzystać z drogi dla pieszych?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 33a ust. 2 ustawy Prawo o ruchu drogowym zabrania korzystania z przejścia dla pieszych przez kierującego urządzeniem transportu osobistego inaczej niż prowadząc je pieszo.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy kierujący urządzeniem transportu osobistego może przejeżdżać przez przejście dla pieszych?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 28 ustawy Prawo o ruchu drogowym oraz zasada szczególnej ostrożności na przejazdach nakazują upewnienie się co do braku zagrożenia niezależnie od stanu zapór.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy dojeżdżając do przejazdu kolejowego masz obowiązek upewnić się czy nie zbliża się pojazd szynowy w sytuacji, w której zapory są podniesione ?' and poprawna = 'TAK';
update question set wyjasnienie = 'Obowiązek zachowania szczególnej ostrożności na przejeździe kolejowym (art. 28 ustawy Prawo o ruchu drogowym) obejmuje obserwację sygnałów świetlnych/dźwiękowych zapowiadających nadjeżdżający pojazd szynowy.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy zbliżając się do przejazdu kolejowego powinieneś zwracać uwagę na sygnały, które mogą wskazywać, że zbliża się pojazd szynowy?' and poprawna = 'TAK';
update question set wyjasnienie = 'Art. 24 ust. 11 ustawy Prawo o ruchu drogowym ogranicza wyprzedzanie na drogach ekspresowych/autostradach dla samochodów o DMC powyżej 3,5 t, gdy różnica prędkości jest niewielka — manewr byłby zbyt długi i ryzykowny.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy poruszając się po drodze ekspresowej dwujezdniowej samochodem ciężarowym o dopuszczalnej masie całkowitej 7 ton wolno Ci wyprzedzić pojazd, który nie wykonuje prac porządkowych i porusza się z niewiele mniejszą prędkością?' and poprawna = 'NIE';
update question set wyjasnienie = 'Pytanie w oryginale ma formę wielokrotnego wyboru (A/B/C) — po sprowadzeniu do tak/nie treść jest niepełna, wymaga przeredagowania lub usunięcia przez admina.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Które z poniższych zachowań świadczy o rozważnym i bezpiecznym prowadzeniu pojazdu?' and poprawna = 'NIE';
update question set wyjasnienie = 'Pytanie w oryginale ma formę wielokrotnego wyboru (A/B/C, wskazanie konkretnego światła) — po sprowadzeniu do tak/nie treść jest niepełna, wymaga przeredagowania lub usunięcia przez admina.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Którego z wymienionych świateł wolno Ci używać, gdy kierujesz samochodem osobowym podczas mgły?' and poprawna = 'NIE';
update question set wyjasnienie = 'Pytanie w oryginale ma formę wielokrotnego wyboru (A/B/C, wskazanie konkretnej czynności) — po sprowadzeniu do tak/nie treść jest niepełna, wymaga przeredagowania lub usunięcia przez admina.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Którą z tych czynności masz obowiązek wykonać podczas wyprzedzania samochodem osobowym we mgle poza obszarem zabudowanym?' and poprawna = 'NIE';
update question set wyjasnienie = 'Art. 24 ust. 2 ustawy Prawo o ruchu drogowym wymaga zachowania niezbędnego odstępu przy WYMIJANIU (ruch w przeciwnym kierunku), ale sztywny wymóg "minimum 1 m" dotyczy OMIJANIA (ten sam kierunek) — stąd poprawna odpowiedź NIE dla wymijania.' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy wymijając hulajnogę elektryczną, jesteś obowiązany zachować odstęp minimum     1 m ?' and poprawna = 'NIE';
update question set wyjasnienie = 'Numer 112 jest jednolitym europejskim numerem alarmowym, obsługiwanym w Polsce przez centra powiadamiania ratunkowego, obejmującym wszystkie służby (Policja, Straż Pożarna, Pogotowie Ratunkowe).' where typ = 'podstawowe'::question_type and media_url is null and tresc = 'Czy numer telefonu 112 jest ogólnopolskim numerem alarmowym dla wszystkich służb ratowniczych?' and poprawna = 'TAK';
